[workspace]
resolver = "2"
members = [
    "libs/interfaces",
    "libs/serializer",
    "gui/src-tauri",
    "cli",
    "server",
]

[workspace.dependencies]
# Internal
interfaces = { path = "./libs/interfaces" }
serializer = { path = "./libs/serializer" }

# External
anyhow = "1"

chrono = "0.4"
clap = { version = "4", features = ["derive"] }

dirs = "6"

log = "0.4"

serde = { version = "1", features = ["derive"] }
serde_json = "1"

toml = "0.8"
