[package]
edition = "2021"
name = "dsm"
version = "0.1.0"

[dependencies]
# Internal
interfaces.workspace = true
serializer.workspace = true
storage.workspace = true

# External
anyhow.workspace = true

bhomz = {workspace = true, features = ["anyhow"]}

clap.workspace = true
colored.workspace = true

log.workspace = true

serde_json.workspace = true

tokio = {workspace = true, features = ["full"]}
toml.workspace = true
