[package]
edition = "2021"
name = "interfaces"
version = "0.2.0"

[dependencies]
anyhow.workspace = true

bhomz = {workspace = true, features = ["anyhow"]}

chrono = {workspace = true, features = ["serde"]}

log.workspace = true

serde = {workspace = true, features = ["derive"]}
serde_json = {workspace = true, features = ["float_roundtrip"] }

toml.workspace = true
