[package]
name = "storage"
version = "0.1.0"
edition = "2024"

[dependencies]
# Internal
interfaces.workspace = true

# External
anyhow.workspace = true

# Azure
azure_core.workspace = true
azure_identity.workspace = true
azure_security_keyvault_secrets.workspace = true
azure_storage.workspace = true
azure_storage_datalake.workspace = true
azure_storage_blobs.workspace = true

chrono.workspace = true

futures.workspace = true

log.workspace = true

reqwest.workspace = true

serde.workspace = true
serde_json.workspace = true