[package]
edition = "2024"
name = "storage"
version = "0.1.0"

[dependencies]
# Internal
interfaces.workspace = true
serializer.workspace = true

# External
anyhow.workspace = true

# Azure
chrono.workspace = true
colored.workspace = true

futures.workspace = true

log.workspace = true

reqwest.workspace = true

serde.workspace = true
serde_json.workspace = true
