name: CI

on:
  push:
    branches:
      - trunk

jobs:
  ci:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'windows-latest'
            args: ''
          # TODO: Linux

    runs-on: ${{ matrix.platform }}
    steps:
      - name: "Setup: Repo"
        uses: actions/checkout@v4

      - name: "Setup: Node"
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: "Setup: Python"
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' 

      - name: "Setup: Rust"
        uses: dtolnay/rust-toolchain@stable

      - name: "Node: fetch packages"
        working-directory: gui
        run: npm ci

      - name: "Rust: Build"
        run: cargo build --workspace --release

      - name: "Rust: Test"
        run: cargo test

      - name: "Rust: Clippy"
        run: cargo clippy -- -D warnings

      - name: "Rust: Format"
        run: cargo fmt --check