name: msi.yml

on:
  push:
    branches:
      - trunk

jobs:
  build-msi:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'windows-latest'
            args: ''

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Build Cli
        run: cargo build --workspace --release

      - name: Npm deps
        run: npm i

      - name: Build Gui
        run: npm run tauri build -- --release

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: msi
          path: |
            target/**/**/**/*.msi