name: msi.yml

on:
  push:
    branches:
      - release

jobs:
  build-msi:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'windows-latest'
            args: ''

    runs-on: ${{ matrix.platform }}
    steps:
      # Setups
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' 

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      # Install dependencies
      - name: Npm Install
        working-directory: gui
        run: npm i

      - name: Install python packages
        working-directory: py-interface
        run: pip install -r requirements.txt

      # Build
      - name: Build Cli
        run: cargo build --workspace --release

      - name: Build Gui
        working-directory: gui
        run: npm run tauri build -- --release

      - name: Build Python Interface
        working-directory: py-interface
        run: maturin build

      # Uploads
      - name: Upload Msi
        uses: actions/upload-artifact@v4
        with:
          name: DataSets-Manager
          retention-days: 5
          path: |
            target/release/bundle/msi/*.msi

      - name: Upload Wheels
        uses: actions/upload-artifact@v4
        with:
          name: Python package
          retention-days: 5
          path: |
            target/wheels/*.whl