name: Release

on:
  push:
    branches:
      - release

jobs:
  python-package:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'windows-latest'
            args: ''
          # TODO: Linux

    runs-on: ${{ matrix.platform }}
    steps:
      - name: "Setup: Repo"
        uses: actions/checkout@v4

      - name: "Setup: Python"
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' 

      - name: "Setup: Rust"
        uses: dtolnay/rust-toolchain@stable

      - name: "Pip: fetch packages"
        working-directory: pyidsm
        run: pip install -r requirements.txt

      - name: "Rust: Generate python interface"
        working-directory: pyidsm
        run: cargo run --bin stub_gen

      - name: "Maturin: build"
        working-directory: pyidsm
        run: maturin build

      - name: "Upload: Wheels"
        uses: actions/upload-artifact@v4
        with:
          name: Python package
          retention-days: 5
          path: |
            target/wheels/*.whl

  build-msi:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'windows-latest'
            args: ''

    runs-on: ${{ matrix.platform }}
    steps:
      - name: "Setup: Repo"
        uses: actions/checkout@v4

      - name: "Setup: Node"
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: "Setup: Rust"
        uses: dtolnay/rust-toolchain@stable

      - name: "Node: fetch packages"
        working-directory: gui
        run: npm i

      - name: "Rust: Build"
        working-directory: cli
        run: cargo build --release

      - name: "Node: Build"
        working-directory: gui
        run: npm run tauri build -- --release

      - name: "Upload: Msi"
        uses: actions/upload-artifact@v4
        with:
          name: DataSets-Manager-MSI
          retention-days: 5
          path: |
            target/release/bundle/msi/*.msi

      - name: "Upload: Exe"
        uses: actions/upload-artifact@v4
        with:
          name: DataSets-Manager-EXE
          retention-days: 5
          path: |
            target/release/bundle/nsis/*.exe